<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DProjects.Factories\DProjects.Factories.csproj" />
    <ProjectReference Include="..\..\src\DProjects.Fs.Abstractions\DProjects.Fs.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\DProjects.Fs.Http\DProjects.Fs.Http.csproj" />
    <ProjectReference Include="..\DProjects.Fs.Test\DProjects.Fs.Test.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
