<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyTitle>DProjects.Text.Yaml</AssemblyTitle>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <AssemblyName>DProjects.Text.Yaml</AssemblyName>
        <OutputType>Library</OutputType>
        <PackageId>DProjects.Text.Yaml</PackageId>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <RootNamespace />
        <ApplicationIcon />
        <OutputTypeEx>library</OutputTypeEx>
        <StartupObject />
        <Company>DProjects</Company>
        <Description>DProjects.Text.Yaml</Description>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <Version>3.0.0</Version>
        <Authors>marcdp</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Copyright>Copyright © DProjects SLU</Copyright>
        <Nullable>enable</Nullable>
        <PackageProjectUrl>https://www.dprojects.com/</PackageProjectUrl>
        <PackageIcon></PackageIcon>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="YamlDotNet" Version="15.1.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\dprojects.datatypes\dprojects.datatypes.csproj" />
      <ProjectReference Include="..\dprojects.serialization.abstractions\dprojects.serialization.abstractions.csproj" />
      <ProjectReference Include="..\dprojects.utils\dprojects.utils.csproj" />
    </ItemGroup>

</Project>
