<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyTitle>DProjects.Db</AssemblyTitle>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <AssemblyName>DProjects.Db</AssemblyName>
        <OutputType>Library</OutputType>
        <PackageId>DProjects.Db</PackageId>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <RootNamespace />
        <ApplicationIcon />
        <OutputTypeEx>library</OutputTypeEx>
        <StartupObject />
        <Company>DProjects</Company>
        <Description>DProjects.Db</Description>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <Version>3.0.0</Version>
        <Authors>marcdp</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Copyright>Copyright © DProjects SLU</Copyright>
        <Nullable>enable</Nullable>
        <PackageProjectUrl>https://www.dprojects.com/</PackageProjectUrl>
        <PackageIcon></PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\dprojects.datatypes\dprojects.datatypes.csproj" />
      <ProjectReference Include="..\dprojects.db.abstractions\dprojects.db.abstractions.csproj" />
      <ProjectReference Include="..\dprojects.factories.abstractions\dprojects.factories.abstractions.csproj" />
      <ProjectReference Include="..\dprojects.fs.abstractions\dprojects.fs.abstractions.csproj" />
      <ProjectReference Include="..\dprojects.text.readers\dprojects.text.readers.csproj" />
      <ProjectReference Include="..\dprojects.text.yaml\dprojects.text.yaml.csproj" />
    </ItemGroup>

</Project>
