<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyTitle>DProjects.Db.Oracle</AssemblyTitle>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <AssemblyName>DProjects.Db.Oracle</AssemblyName>
        <OutputType>Library</OutputType>
        <PackageId>DProjects.Db.Oracle</PackageId>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <RootNamespace />
        <ApplicationIcon />
        <OutputTypeEx>library</OutputTypeEx>
        <StartupObject />
        <Company>DProjects</Company>
        <Description>DProjects.Db.Oracle</Description>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <Version>3.0.0</Version>
        <Authors>marcdp</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Copyright>Copyright © DProjects SLU</Copyright>
        <Nullable>enable</Nullable>
        <PackageProjectUrl>https://www.dprojects.com/</PackageProjectUrl>
        <PackageIcon></PackageIcon>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Oracle.ManagedDataAccess" Version="23.8.0" />
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\DProjects.Db\DProjects.Db.csproj" />
    </ItemGroup>


</Project>
