<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyTitle>DProjects.Log</AssemblyTitle>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <AssemblyName>DProjects.Log</AssemblyName>
        <OutputType>Library</OutputType>
        <PackageId>DProjects.Log</PackageId>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <RootNamespace />
        <ApplicationIcon />
        <OutputTypeEx>library</OutputTypeEx>
        <StartupObject />
        <Company>DProjects</Company>
        <Description>DProjects.Log</Description>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <Version>3.0.0</Version>
        <Authors>marcdp</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Copyright>Copyright © DProjects SLU</Copyright>
        <Nullable>enable</Nullable>
        <PackageProjectUrl>https://www.dprojects.com/</PackageProjectUrl>
        <PackageIcon></PackageIcon>
        <CLSCompliant>true</CLSCompliant>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" /> 
        <PackageReference Include="System.Threading.Channels" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DProjects.Factories.Abstractions\DProjects.Factories.Abstractions.csproj" />
      <ProjectReference Include="..\DProjects.Fs.Abstractions\DProjects.Fs.Abstractions.csproj" />
      <ProjectReference Include="..\DProjects.Log.Abstractions\DProjects.Log.Abstractions.csproj" />
    </ItemGroup>

</Project>
