<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyTitle>DProjects.Log.Storage</AssemblyTitle>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <AssemblyName>DProjects.Log.Storage</AssemblyName>
        <OutputType>Library</OutputType>
        <PackageId>DProjects.Log.Storage</PackageId>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <RootNamespace />
        <ApplicationIcon />
        <OutputTypeEx>library</OutputTypeEx>
        <StartupObject />
        <Company>DProjects</Company>
        <Description>DProjects.Log.Storage</Description>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <Version>3.0.0</Version>
        <Authors>marcdp</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Copyright>Copyright © DProjects SLU</Copyright>
        <Nullable>enable</Nullable>
        <PackageProjectUrl>https://www.dprojects.com/</PackageProjectUrl>
        <PackageIcon></PackageIcon>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="LogEntryReaderAuto.cs" />
      <Compile Remove="LogEntryReaderClassic.cs" />
      <Compile Remove="LogEntryReaderCsv.cs" />
      <Compile Remove="LogEntryReaderDirTail.cs" />
      <Compile Remove="LogEntryReaderFiles.cs" />
      <Compile Remove="LogEntryReaderFilter.cs" />
      <Compile Remove="LogEntryReaderFsFileTail.cs" />
      <Compile Remove="LogEntryReaderJson.cs" />
      <Compile Remove="LogEntryReaderRat.cs" />
      <Compile Remove="LogEntryReaderRaw.cs" />
      <Compile Remove="LogEntryReaderW3C.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DProjects.Factories.Abstractions\DProjects.Factories.Abstractions.csproj" />
      <ProjectReference Include="..\DProjects.Fs.Abstractions\DProjects.Fs.Abstractions.csproj" />
      <ProjectReference Include="..\DProjects.Log.Abstractions\DProjects.Log.Abstractions.csproj" />
      <ProjectReference Include="..\DProjects.Log.storage.Abstractions\DProjects.Log.storage.Abstractions.csproj" />
      <ProjectReference Include="..\DProjects.Text.Json\DProjects.Text.Json.csproj" />
    </ItemGroup>

</Project>
