<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyTitle>DProjects.XVault</AssemblyTitle>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <AssemblyName>DProjects.XVault</AssemblyName>
        <OutputType>Library</OutputType>
        <PackageId>DProjects.XVault</PackageId>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <RootNamespace />
        <ApplicationIcon />
        <OutputTypeEx>library</OutputTypeEx>
        <StartupObject />
        <Company>DProjects</Company>
        <Description>DProjects.XVault</Description>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <Version>3.0.0</Version>
        <Authors>marcdp</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Copyright>Copyright © DProjects SLU</Copyright>
        <Nullable>enable</Nullable>
        <PackageProjectUrl>https://www.dprojects.com/</PackageProjectUrl>
        <PackageIcon></PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        
        <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
        
        <PackageReference Include="Isopoh.Cryptography.Argon2" Version="2.0.0" />
        
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.7" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.7" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.7" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.7" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DProjects.Crypto\DProjects.Crypto.csproj" />
      <ProjectReference Include="..\DProjects.Text.Yaml\DProjects.Text.Yaml.csproj" />      
    </ItemGroup>
 

</Project>
